### ISSUE TITLE
Implement analytics on top of `InputSource` abstraction

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#1048]
Should be synchronous in the beginning, we can split them into tasks later.

We should start with the prototypical analytics first (for the different use cases first):

* [x] Addresses with balance (ledger state)
* [x] Payload types (tangle level)
* [x] Ledger size (#1060)

Keep _daily active addresses_ in mind.

**Comment by Alexandcoats** [comment]
Closed by #1061
