### ISSUE TITLE
Input-output distribution of UTXO transactions in IOTA

### ISSUE THREAD

**Issue by polinikita** [iotaledger/inx-chronicle#1129]
## Description

A feature that provides the input-output distribution of UTXO transactions in IOTA

## Motivation

To simulate a random reality-based UTXO ledger, it is desirable to understand the basic properties of transactions created in IOTA in past years. The most basic property of a random transaction is its input and output degrees.

## Requirements

**Basic requirements:** 
Compute the distribution on pairs <_input_degree_, _output_degree_> using the following buckets
**BucketSet** = {{0}, {1}, {2}, {3}, ..., {7}, {8,9,...,15}, {16,17,..., 31}, {32,33,...,63}, {64,65,...,127}}.
There should be possible to retrieve Distribution[X,Y] with X, Y\in **BucketSet** where **Distribution**[X,Y] shows the number of transactions whose input degree is from X and the output degree is from Y.
Ensure that there is no X,Y with |X|>1 or |Y|>1 such that Distribution[X,Y] > 0.001 * numberOfAllTransactions

**Standard requirements:**
Same as above with no groups containing more than one integer

**Advanced requirements:**
The distribution of input/output degrees of conflicting transactions.

## Open questions (optional)
Personally, I would prefer the advanced requirements. Now I simulate a random reality-based ledger by creating inputs and outputs as uniform random variables on small sets. 

<img width="364" alt="Untitled" src="https://user-images.githubusercontent.com/91725722/218493365-cc329c6c-df6a-4144-9f5e-012b06b37395.png">

## Are you planning to do it yourself in a pull request?

No.

**Comment by Alexandcoats** [comment]
Closed by #1049
