### ISSUE TITLE
Chronicle doesn't return outputs compared to Hornet

### ISSUE THREAD

**Issue by msarcev** [iotaledger/inx-chronicle#1165]
### Bug description

There is a case found where the response from Chronicle is different from the Hornet response.

Endpoint: `/api/indexer/v1/outputs/basic`

Usage with `tag` query param.

Example:
tag: "Soonaverse" (0x536f6f6e617665727365)
Chronicle -> https://chronicle.testnet.shimmer.network/api/indexer/v1/outputs/basic?tag=0x536f6f6e617665727365
VS
Hornet -> https://api.testnet.shimmer.network/api/indexer/v1/outputs/basic?tag=0x536f6f6e617665727365

### Steps to reproduce the bug

1. View and compare the responses of links above

### Expected behaviour

Chronicle should return the outputs. Response should be identical as when using Hornet for same input.

### Actual behaviour

Chronicle return an empty array.

**Comment by Alexandcoats** [comment]
Our API accepts the string tag, not the bytes.

https://chronicle.testnet.shimmer.network/api/indexer/v1/outputs/basic?tag=Soonaverse

If this is not acceptable, let us know.
