### ISSUE TITLE
Opening public route does not work as expected / documented

### ISSUE THREAD

**Issue by HolgerKoether** [iotaledger/inx-chronicle#1218]
### Bug description

Adding a public route (in order to disable JWT authentication) by adding `--public-route=/api/*` or `--public-route=*` does not work. When querying the URL (e.g. http://135.181.40.39:14265/api/explorer/v2/milestones/by-index/30/blocks) the error message 
`{"error":{"code":"400","message":"missing or malformed jwt, error: code=400, message=missing or malformed jwt"}}`
appears

Used documentation:
https://wiki.iota.org/shimmer/chronicle/reference/authentication/

![2023-04-03 17_51_18-root@ubuntu-32gb-hel1-1_ __inx-chronicle_docker](https://user-images.githubusercontent.com/48596312/229882004-61a5a352-1c25-4e02-a91b-139ae09d3bd3.png)

### Rust version

- Rust version:

### Chronicle version

- Chronicle version (version number, commit, or branch): latest branch

### Hardware specification

- Operating system:
- RAM: 32GB
- Cores: 8
- Device: 240GB SSD
- Ubuntu 22

### Steps to reproduce the bug

1. see above (happy to share root access to the test system)
2. 
3. 

### Expected behaviour

Chronicle returns the respective data

### Actual behaviour

the jwt token is still required

### Errors

```
`{"error":{"code":"400","message":"missing or malformed jwt, error: code=400, message=missing or malformed jwt"}}`
```

**Comment by Alexandcoats** [comment]
The route requires that it is surrounded by quotes. Have you tried `- "--public-route='*'"` or `- "--public-route='/api/*'"`?

**Comment by HolgerKoether** [comment]
yes, the same result.

**Comment by HolgerKoether** [comment]
the correct parameter is `- "--public-route=api/*"`
