### ISSUE TITLE
Nodeinfo response missing required field `supportedProtocolVersions`

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger/inx-chronicle#1302]
### Bug description

Nodeinfo response missing required field `supportedProtocolVersions`
Issue found here https://github.com/iotaledger/iota-sdk/issues/1614

### Chronicle version

- Chronicle version (version number, commit, or branch): 1.0.0-rc.2

### Steps to reproduce the bug

1. Get the info

### Expected behaviour

Adhere to https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/main/tips/TIP-0025/core-rest-api.yaml

### Actual behaviour

Missing a field

**Comment by DaughterOfMars** [comment]
The info response for chronicle is simply different from the one for nodes. This is intentional, not a bug.
