### ISSUE TITLE
Investigate and fix the Explorer balance endpoint (Nova)

### ISSUE THREAD

**Issue by msarcev** [iotaledger/inx-chronicle#1336]
### Bug description

The endpoint for Explorer address balance (Nova) doesn't return results.

`[chronicle-nova-endpoint]/api/explorer/v3/balance/rms1qztphdk2lgx80d43zp3ck0elerwmytn4jy4strpcxem7entenmyzws9z6p7`

### Chronicle version

- Chronicle version (version number, commit, or branch):  `2.0`

### Hardware specification

- Operating system:
- RAM:
- Cores:
- Device:

### Steps to reproduce the bug

1. Check the link, that address should have balance (if the network was reset, try any other address with and AUC associated output)

### Expected behaviour

Balance data returned

### Actual behaviour

No results returned

**Comment by DaughterOfMars** [comment]
Ready to close?
