### ISSUE TITLE
Investigate and fix Explorer ledger-updates endpoint (Nova)

### ISSUE THREAD

**Issue by msarcev** [iotaledger/inx-chronicle#1337]
### Bug description

The endpoint for Explorer "ledger updates" (TX history) doesn't return results.

`[chronicle-nova-endpoint]/api/explorer/v3/ledger/updates/by-address/rms1pptg5vur0aj84e4d5ksc6tw5ex6f8jt2aht82kkr872dngkguq8tktqffj7`

### Chronicle version

- Chronicle version (version number, commit, or branch):  `2.0`

### Steps to reproduce the bug

1. Check the link, that address should have balance (if the network was reset, try any other address with and AUC associated output)

### Expected behaviour

Balance data returned

### Actual behaviour

No results returned

**Comment by DaughterOfMars** [comment]
Ready to close this?
