### ISSUE TITLE
Add staker statistics: candidates (Nova) [medium]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/inx-chronicle#1347]
## Description

> **Priority**: medium

This is part 2 of 3 statistics we would like to have for Nova. For this statistics, we would like to track how many candidated there are. 

The 3 parts are:
1. validators in committee
2. candidates
3. total

Afaik, this needs an INX endpoint

## Motivation

Improve statistics to accomodate to new IOTA 2.0 features, like staker statistics

## Requirements

1. 
2. 
3. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
Implemented in features analytics.
