### ISSUE TITLE
Add staker statistics: total (Nova) [medium]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/inx-chronicle#1348]
## Description

> **Priority**: medium

This is part 3 of 3 statistics we would like to have for Nova. For this statistics, we would like to track how many staker there are, this means account outputs with the staking feature on. 

The 3 parts are:
1. validators in committee
2. candidates
3. total

Afaik, this needs an INX endpoint

## Motivation

Improve statistics to accomodate to new IOTA 2.0 features, like staker statistics

## Requirements

1. 
2. 
3. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
This is currently implemented via the features analytics
