### ISSUE TITLE
Add delegation/staking statistics: total staked (Nova) [medium]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/inx-chronicle#1350]
## Description

> **Priority**: medium

This is part 1 of 4 statistics we would like to have for delegation/staking statistics. The idea of this feature is to know how much is staked in total in the staking feature of all accounts

The 4 parts are:
1. total staked
2. total staked in committee
3. total delegated
4. total delegated in committee

## Motivation

Improve statistics to accomodate to new IOTA 2.0 features, like delegation/staking statistics

## Requirements

1. 
5. 
6. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
This is implemented in the features measurement
