### ISSUE TITLE
Add delegation/staking statistics: total delegated (Nova) [medium]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/inx-chronicle#1352]
## Description

> **Priority**: medium

This is part 3 of 4 statistics we would like to have for delegation/staking statistics. The idea of this feature is to know how much delegated in total, how much is the sum of all delegation outputs

The 4 parts are:
1. total staked
2. total staked in committee
3. total delegated
4. total delegated in committee

## Motivation

Improve statistics to accomodate to new IOTA 2.0 features, like delegation/staking statistics

## Requirements

1. 
6. 
7. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
This is implemented as part of the ledger outputs analytic
