### ISSUE TITLE
Add RMC statistics (Nova) [low]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/inx-chronicle#1354]
## Description

> **Priority**: low

Add RMC statistics

## Motivation

N/A

## Requirements

1. 
2. 
3. 

## Open questions (optional)

N/A

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
Added a `iota_slot_commitments` measurement with the reference mana cost

**Comment by begonaalvarezd** [comment]
> Added a `iota_slot_commitments` measurement with the reference mana cost

Does this mean we can close this issue?

**Comment by DaughterOfMars** [comment]
If you think that satisfies your requirements. The measurement simply contains the RMC per slot.

**Comment by begonaalvarezd** [comment]
> If you think that satisfies your requirements. The measurement simply contains the RMC per slot.

thanks
