### ISSUE TITLE
Include total items in blocks per slot endpoint (Nova) [none]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/inx-chronicle#1355]
## Description

> **Priority**: none

Add the total number of items in the response to avoid clients exhausting the cursor to be able to know the total size. 
We should study if this impacts the performance of chronicle, and if it does, we can close this issue and we can continue using it as we currently do

## Motivation

Improve usage

## Requirements

1. 
6. 
7. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
Implemented. The route will get the count before getting the stream, so this comes with some caveats:
1. The count may not match the actual total if you were to exhaust the stream.
2. The count may change each time you get the next page of results.

Still, I think this is as good as it is possible to be.

**Comment by begonaalvarezd** [comment]
We will only request the blocks for past slots, so we dont expect the sum to change over time since the blocks are already issued and the slot is in the past, can this still be an edge case we might experience?

**Comment by DaughterOfMars** [comment]
Good point. I don't think it can be wrong in that case.
