### ISSUE TITLE
Optimize rich-list endpoint list by storing only the most recent version (Nova) [none]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/inx-chronicle#1357]
## Description

> **Priority**: none

The rich-list stores everything but we only just use the most recent version. We could optimize and improve chronicle by just keeping the most recent version

## Motivation

Cleanup

## Requirements

1. 
6. 
7. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
Implemented!
