### ISSUE TITLE
Include raw stored mana (undecayed) in the address mana balance endpoint (Nova) [low]

### ISSUE THREAD

**Issue by begonaalvarezd** [iotaledger/inx-chronicle#1361]
## Description

> **Priority**: low

`/api/explorer/v3/balance/[address]` returns eg
```
{
    "totalBalance": {
        "amount": "85567958",
        "mana": {
            "stored": "374782896",
            "potential": "683261"
        }
    },
    "availableBalance": {
        "amount": "85567958",
        "mana": {
            "stored": "374782896",
            "potential": "683261"
        }
    },
    "ledgerIndex": xxxx
}
````

It would be good to include the undecayed stored mana too so we can show users how much its decayed 

## Motivation

Provide decay in mana balance

## Requirements

1. 
2. 
3. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by DaughterOfMars** [comment]
Implemented by separating the field into `stored_mana` and `decayed_mana` which contains both decayed stored and potential.
