### ISSUE TITLE
Blocks by slot-index returns the same cursor

### ISSUE THREAD

**Issue by brancoder** [iotaledger/inx-chronicle#1362]
### Bug description

Blocks by endpoint always returns the same results and cursor
ex.
https://chronicle.iota2-alphanet.iotaledger.net/api/explorer/v3/commitments/by-index/44249/blocks

### Rust version

- Rust version:

### Chronicle version

- Chronicle version (version number, commit, or branch): 

### Hardware specification

- Operating system:
- RAM:
- Cores:
- Device:

### Steps to reproduce the bug

send subsequent requests to the provided link with returned cursor

### Expected behaviour

cursor not returned on the last page

### Actual behaviour

cursor always returned

### Errors

```
Paste error here
```

**Comment by begonaalvarezd** [comment]
@DaughterOfMars This issue can be closed
