### ISSUE TITLE
Provide additional Prometheus metrics

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#147]
We can carry over the ones from this PR: https://github.com/iotaledger/inx-chronicle/pull/61

**Comment by Alexandcoats** [comment]
We should also add the following:
- Channel metrics from https://github.com/iotaledger/bee/pull/1405
- Synced milestones count
- Failed to solidify count

**Comment by grtlr** [comment]
We probably also want query times and number of API calls per endpoint.

**Comment by grtlr** [comment]
Closed by #577.
