### ISSUE TITLE
Manually set actor names

### ISSUE THREAD

**Issue by Alexandcoats** [iotaledger/inx-chronicle#151]
We should probably set the actor names manually so that they will appear less verbose in the tokio console

**Comment by grtlr** [comment]
You mean statically? :trollface:

**Comment by Alexandcoats** [comment]
> You mean statically? :trollface:

No, haha, I mean we should override the default `name` method because the `std::any::type_name` strings are very long since they contain the path.

**Comment by Alexandcoats** [comment]
Closed by #204
