### ISSUE TITLE
Enabled metrics should be configurable via features

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#167]
There are two different kinds of metrics, the ones we use for debugging our implementation and ones that are used in production to monitor the node.

**Comment by Alexandcoats** [comment]
Would it perhaps be better to have multiple features for metrics, since adding them usually requires different data structures (see the channels) and this may be best determined at compile time.

**Comment by grtlr** [comment]
I agree, similar to `tokio-console`, the channel-based metrics should not be exposed to the user. So they can be put behind a feature flag.

In general, I think we should be careful adding new features because they can become unwieldy.
