### ISSUE TITLE
Use MongoDB `insert_*` over `update_*` where it makes sense

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#218]
Using `update` is prone to silent overwriting of messages. We should think about when that can happen and prefer using `insert`, even though that might require us to perform work using transactions.

**Comment by Alexandcoats** [comment]
There should never be a time when silent overwriting of messages is a problem.

**Comment by grtlr** [comment]
Now that we have the version check and database name in the config I too believe that we don't need this anymore.
