### ISSUE TITLE
Fix and re-enable `metrics` locally and in Docker

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#229]
In earlier versions of Chronicle the following warnings and errors came up:

Warnings:

```
Cannot update process metrics: No such file or directory (os error 2)
```

Error:

```
panicked at `called `Result::unwrap()` on an `Err` value ... (/inx-chronicle/src/db/mongodb.rs)
```

**Comment by Alex6323** [comment]
Issue is too old and unspecific. The metrics so far supported by Chronicle (`db size metric`) do work without the above mentioned warnings/errors.
