### ISSUE TITLE
Return proper `ledger_index` in `OutputMetadataResponse`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#319]
The field `OutputMetadataResponse::ledger_index` describes:

> The current ledger index for which the request was made.

To properly set this field we need to store the latest `MilestoneIndex` from `proto::ListenToLedgerUpdates` in a Chronicle-wide state object that is also shared with the API and retrieved from there. Alternatively, we could also perform a more complex DB query.

**Comment by Alexandcoats** [comment]
Oof. I suppose we could add a table for this, or load it into memory at startup from the blocks table.
