### ISSUE TITLE
Move `children/` endpoint to `explorer` API

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#321]
As `children` is not part of the Core Node API anymore, we should think about adding it to the `history` API and update the [corresponding TIP](https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/explorer-api/tips/TIP-0036/history-rest-api.yaml) accordingly.

**Comment by Alexandcoats** [comment]
History seems like a weird place for it. Is there really any reason we can't include additional routes in our impl of the core API?
