### ISSUE TITLE
Provide a feature to recreate / change indices

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#337]

**Comment by Alexandcoats** [comment]
After some experimentation and thought, I think our best option is to provide migration scripts (`.mongodb`) files whenever we make changes to the schema. This will provide a clear upgrade path and avoid weirdness in the application logic.

**Comment by grtlr** [comment]
I agree, for simple things we can provide migration scripts, more complicated scripts could live within the Rust code and be deprecated after a couple of releases again. I'm going to close this for now because it's not actionable.
