### ISSUE TITLE
Create functions for aggregation stages

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/inx-chronicle#342]
This has the following advantages:
* reduces risk for bugs;
* single stages can be reused by different aggregations instead of repeating the same query document;
* stages are implicitly documented via function names which would make the code more readable;

**Comment by grtlr** [comment]
I think this makes total sense for the stages that are general enough.

**Comment by grtlr** [comment]
I'm closing this because it is not actionable right now. We can always re-open later.
