### ISSUE TITLE
Use `ListenToLedgerUpdates` together with `ReadUnspentOutputs`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#347]
By listening to ledger updates through `ListenToLedgerUpdates` we get all the ledger updates, but we never get the initial state of the ledger. This is a problem because there may exist unspent outputs that were created in milestones that might be pruned by the node already—and therefore will never show up in the resulting stream. Because of this, we need to additionally call `ReadUnspentOutputs` to get the complete ledger with all unspent outputs (the nodes themselves get this information from the snapshot files).

There is an additional twist though. `ReadUnspentOutputs` yields a stream of `UnspentOutput`s that contain a `ledgerIndex` field that denotes the ledger index for which this `UnspentOutput` was valid. Note that this is closely related to the `ledger_index` in the `OutputMetadata` responses. Essentially, this field specifies the current ledger index of the node when the request was made. The tricky part is that this will be newer than the requested range of milestones from `ListenToLedgerUpdates`.

@alexsporn, @muXxer Can you please confirm this description? I don't want to make any mistakes here.

**Comment by alexsporn** [comment]
`ReadUnspentOutputs` asks the node to send you it's current ledger state include the milestone index from when this ledger state was valid.

`ListenToLedgerUpdates` will give you the diffs that you can apply to the ledger state to bring the state forward to a newer milestone (or even backwards to the past).

I think it is important to understand that the Ledger is not just data, but contains a **state**, and we ought to not just keep the data but also this state in a consistent way.

**Comment by muXxer** [comment]
Also you will never get the initial outputs from the genesis snapshot by only using `ListenToLedgerUpdates`.

**Comment by grtlr** [comment]
Thank you for the quick answers! I have another quick conceptual question: An output can transition from `unspent` to `spent` back to `unspent`, when the output was created for a second time in a later block?

**Comment by grtlr** [comment]
@Alexandcoats To see if our soltuion works we can issue an request against for the "genesis output":

```sh
curl .../api/core/v2/outputs/0x00000000000000000000000000000000000000000000000000000000000000000000 | jq
```

This output is not part of a block, but comes from the genesis snapshot.
