### ISSUE TITLE
Use transactions and batch insert to write cones to the database

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#348]
@Alexandcoats wrote:

> The validity of this index is defined by its existence in the database, meaning that the milestone was successfully added. However, because we are not using transactions, there are several things that can go wrong.
>
> 1. We request an output which was inserted, but the milestone was not yet. Very slim chance, but technically possible. In this case the query would likely fail with a 500 error because we expect the value to exist.
> 2. We request an output which is unspent on milestone N, spent on N+X. The data returned may reflect the spent status, though the milestone was not yet inserted. Again, this would probably return a 500 error. Alternatively, we may get the unspent data but N+X ledger index because the data and milestone could be inserted between the first match and the lookup. This would not return an error in the API, but would instead return invalid results.
>
> Because there is no alignment between reads and writes, we cannot trust some of our queries to function properly. For instance, the query I wrote for getting the ledger index returns invalid data half of the time because it contains lookups and data can be inserted between them.

We should use MongoDB's transactions together with a batch insert to write milestone cone streams to the database.

Please note that this does not solve all problems with the ledger index, as outlined in #347.

**Comment by grtlr** [comment]
There seems to be a limitation with the Rust driver of MongoDB. From the [crate documentation](https://docs.rs/mongodb/latest/mongodb/struct.ClientSession.html#method.start_transaction):

> Transactions are supported on MongoDB 4.0+. The Rust driver currently only supports transactions on replica sets.

**Comment by grtlr** [comment]
@Alexandcoats I'm currently working on this.

**Comment by Alexandcoats** [comment]
You say it is important, but can you provide an actual reason?

**Comment by Alexandcoats** [comment]
This is a use-case for a node, not for chronicle though. Any client wanting this information should not rely on an archival tool for it.

**Comment by grtlr** [comment]
Chronicle will not only be used for archival purposes. It will end up powering the Explorer and maybe even Firefly. From the outside it has to look like a regular node that never prunes.

**Comment by Alexandcoats** [comment]
> The clients have to know for which `ledger_index` an output is unspent if they want to reconstruct the ledger state. The reason for this is that an output could be spent right after a request was made.
> 
> Now consider the following scenario: Let's say a client wants to show the ledger state (for example to compute the balance of an account). For this, it has to call `/api/core/v2/outputs/{outputId}/metadata` multiple times. The balance is only guaranteed to be valid if all of these calls return the same ledger index.
> 
> Basically, a Rest API in general does not follow ACID principles. In the example above the _consistency_ (C) property is violated. The `ledger_index` gives clients the chance to at least catch these cases.

In what way does using the created/spent-at milestone not satisfy this condition? In fact, it would significantly improve the situation because the ledgwer index would not change every 10 seconds, but only once the output has actually been spent.
