### ISSUE TITLE
Move some repeatedly used `&'static str`s into constants.

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/inx-chronicle#353]

**Comment by Alexandcoats** [comment]
Specifics pls

**Comment by Alex6323** [comment]
It's mostly in the queries where we repeatedly use "milestone_index", "milestone_timestamp", "output_id", etc. We could put those repeatedly uses specifiers into constants to reduce risk of weird errors due to typos.
E.g. "milestone_index" is repeated 18 times in our codebase.

**Comment by grtlr** [comment]
Could this be similar to the macro that I'm using in `bee-inx`?

So that we could write `field!(metadata.output_id): output_id` in MongoDB queries.
