### ISSUE TITLE
Use `#[serde(rename_all = "camelCase")]` on the struct instead of individual field renaming

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/inx-chronicle#372]
It's very rare that we would give a field an absolutely different name, so an explicit field renaming is most often just noise that we can get rid off if we place `#[serde(rename_all = "camelCase")]` on the struct itself once. This also has the additional benefit, that if a field is added it will be automatically renamed as well consistent with the other fields, so reduces the risk for bugs like we had before when a request wouldn't be properly mapped on the according type leading to inappropriate API responses.

**Comment by Alexandcoats** [comment]
Cool, didn't know this was an option.
