### ISSUE TITLE
Balance endpoint for Explorer API

### ISSUE THREAD

**Issue by lzpap** [iotaledger/inx-chronicle#382]
TODO: define how exactly it works, should only sum up balance owned without conditions.
 - chronicle expose API
 - either compute it on the fly, or keep balance updates for each milestone
 - what consitutes to the balance? @lzpap

**Comment by grtlr** [comment]
@iotaledger/chronicle The easiest way to do this is probably to add an aditional field `amount` to `LedgerUpdateDocument`, then we can do the balance calculation completely in MongoDB.

**Comment by grtlr** [comment]
:tada: @Alex6323 already prepared an PR for this: #388.

**Comment by lzpap** [comment]
Two categories: Balance available rn, balance not accesible rn
