### ISSUE TITLE
Report summary of the syncing progress to `log::info`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#390]
Right now, we report successful syncing of a milestone to `log::debug` for each milestone. In addition to that, we should log summary information about the syncing status to `log::info`. This could either be:

* Write out a log entry every N messages.
* While syncing is active, report the `SyncStatus` every M seconds.

For regular users, the debug information is probably to verbose and might even slow down the syncing process.

**Comment by Alexandcoats** [comment]
Do we still want something like this?

**Comment by grtlr** [comment]
Eventually yes, but I'm closing this for now as there are more important things to focus on.
