### ISSUE TITLE
Consider using `#[serde(deny_unknown_fields)]` for API extractors

### ISSUE THREAD

**Issue by Alexandcoats** [iotaledger/inx-chronicle#483]
## Description

This [attribute](https://serde.rs/container-attrs.html#deny_unknown_fields) will stop users from sending parameters to endpoints that are unexpected. Here is an example of the generated error:

```
GET http://localhost:8000/api/analytics/v2/transactions?startTimestamp=1658756560&end_timestamp=1658856560

400 Bad Request
{
  "code": 400,
  "message": "Failed to deserialize query string: unknown field `end_timestamp`, expected `startTimestamp` or `endTimestamp`"
}
```

## Motivation

I have, on several occasions, sent `snake_case` params when I should have sent `camelCase`. This is currently ignored by the API silently, so you may believe you have received valid data when in fact you have not.

**Comment by grtlr** [comment]
This is super cool. If it's only about adding this attribute I'm all for it.
