### ISSUE TITLE
Tracking Issue - `Shimmer RC`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#486]
### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter.

### Steps

* [ ] #565
* [x] Add `ProtocolUpdateDocument` collection
* [x] Implement better gap reporting

### Unresolved Questions

How should we adapt our types to fit the new data model? We can't really deserialize to a `Block` that contains `OutputId`s instead of `Output`s anymore.

### Implementation history

None.

**Comment by Alexandcoats** [comment]
Protocol update added by #500

**Comment by grtlr** [comment]
Closing this in favor of the individual issues.
