### ISSUE TITLE
Document MongoDB `transactionLifetimeLimitSeconds` configuration

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#559]
When we call `ReadUnspentOutputs` the resulting transaction can take a really long time, depending on the amount of outputs. In some cases, the default timeout from MongoDB kills the transaction before completion. To work around this, users should configure their MongoDB instance with a larger timeout using the `transactionLifetimeLimitSeconds` option.

We should document that behavior, provide an example on how to set the flag, and adapt our `docker-compose.yml` file accordingly.

**Comment by Alexandcoats** [comment]
Should we perhaps create special logic for this process that happens only one time?

**Comment by grtlr** [comment]
We don't have transaction anymore, so this can be closed.
