### ISSUE TITLE
Check `.is_empty()` for all occurences of `insert_many`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#583]
When the iterator passed to `insert_many` is empty, MongoDB will through an error. Alternatively, we could also match on the error returned by `insert_many`.

**Comment by Alexandcoats** [comment]
Another option which I explored in #566 is to use a chunks iter over the inserts. This will accomplish two things:

1. We will not try to insert an empty array.
2. We will not try to insert too many records at once.

**Comment by grtlr** [comment]
Yeah, that's even better

**Comment by grtlr** [comment]
This is solved indirectly by batching.
