### ISSUE TITLE
Fix indexer foundry ID route not returning array

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/inx-chronicle#584]
[Indexer route `/api/indexer/v1/outputs/foundry/{foundryId}` returns an array containing the output ID](https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/tips/indexer-api/tips/TIP-0026/indexer-rest-api.yaml) but Chronicle returns the output id directly as the value.

expected:
```
{
  ledgerIndex: 622037,
  pageSize: 0,
  items: [
    '0x8439fc69c98e36290315b4472e64409ceb2757804399b0edf5b3727ed0f41fe60100'
  ]
}
```

got:
```
{
  ledgerIndex: 622055,
  outputId: '0x8439fc69c98e36290315b4472e64409ceb2757804399b0edf5b3727ed0f41fe60100'
}
```

**Comment by msarcev** [comment]
Please also check all other endpoints for the same issue.
