### ISSUE TITLE
Add endpoint to efficiently query associated outputs of an address

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/inx-chronicle#638]
This is a requirement coming from the explorer team: On an address page, we load up the outputs which are associated to an address given whether the address occurs in any output's unlock conditions or features (means also outputs which are not owned by the given address). The current implementation on the explorer's side involves querying the indexer API with multiple requests in parallel to create a list of output IDs and then, on the frontend, load up the output ID's data given the output ID to show things like the amount and in which unlock condition/feature the address occurred in. Like the transaction history, the display of these associated outputs is ordered by the creation date.

Unfortunately the current implementation only works while the number of associated outputs is low as there is no way for pagination to happen since the indexer does not support any sorting of outputs by creation date. This means that while the number of associated outputs is low, the frontend can simply calculate the ordering after having fetched the actual outputs but this again breaks and is extremely slow as more outputs are available. As a workaround, the explorer will implement this functionality like this only for addresses where the number of associated outputs is under some bound and otherwise show a warning that the data can not be displayed as there is too much to fetch.

Chronicle therefore should implement a specific explorer API, which given an address, returns a paginated response of output IDs sorted by creation date (newest first) where the given address occurs in an output's unlock conditions or features. With this, the frontend code can simply load up the data per page instead.

**Comment by Alexandcoats** [comment]
> Unfortunately the current implementation only works while the number of associated outputs is low as there is no way for pagination to happen since the indexer does not support any sorting of outputs by creation date

I'm not sure what you mean. The built-in sort is by booked milestone index.

**Comment by grtlr** [comment]
This is currently not planned as the Explorer panel that uses this endpoint will change significantly. We can revisit this once we have concrete requirements—I'm closing this until then.
