### ISSUE TITLE
Find optimizations for and cleanup stream iterators

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#704]
I think we should be able to gain performance in syncing by performing concurrent writes for chunks. Currently, we are only doing this for the initial ledger state.

Since we use this in multiple places we should come up with a good abstraction that can be reused.

**Comment by Alexandcoats** [comment]
Look into reusing code for stream compositions in the INX worker.

**Comment by Alex6323** [comment]
I am still looking into it. The issue is not specific enough IMO to be actionable.

**Comment by Alexandcoats** [comment]
We already have about as good performance from the streams as we'll get now that they all operate in parallel. The only thing potentially remaining is to consolidate code, but tbh I don't think it's possible to do it in a clean way. Or, rather, the current method using stream mappers is the cleanest (and most idiomatic) way.

**Comment by grtlr** [comment]
Yeah, I don't really see a way forward (nor a necessity). Closing this for now.
