### ISSUE TITLE
More flexible syncing by providing administrative functionality

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#727]
Right now, we only offer the option to specify a syncing milestone from which INX starts syncing. 

We should create a new `[sync]` section in the `Config` that gives users more flexibility:

* `sync_start_milestone = 1` should move to that section
* Add an additional option `delete_newer` that would delete any data that is newer than that milestone

The motivation behind this is, that if there was a problem with Chronicle and we know a safe milestone (like 1 week ago, the milestone before the update) the user can only do a partial wipe of the DB and does not have to resync everything from scratch.

**Comment by Alexandcoats** [comment]
Feels like perhaps that should be part of the CLI, rather than config.
