### ISSUE TITLE
Allow specifying the context using an associated type

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/inx-chronicle#741]
## Description

#729 once merged introduces context dependent conversion traits like `TryFromWithContext` which depend on a `ProtocolParameters` type that describes this context. Instead of a direct dependency on that type we should specify the context through an associated type.

## Motivation

Better trait design.

## Are you planning to do it yourself in a pull request?

Yea, can do that.

**Comment by grtlr** [comment]
Closing this for now.
