### ISSUE TITLE
Add analytics query for addresses that hold a balance

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#749]
It might be interesting to see how the ledger state (with regards to addresses) evolves over time. Note that this is different from `totalActiveAddresses`.

**Comment by Alexandcoats** [comment]
Could you add design specs to this issue?

**Comment by grtlr** [comment]
We basically want the number of unique addresses that owned unspent outputs at a given milestone. Since we only want to have this on a per-milestone basis we need to add a new endpoint under `ledger`.

**Comment by Alexandcoats** [comment]
Yes, but I mean add the expected endpoint, the format of the output, etc.

**Comment by Alexandcoats** [comment]
This should be specified as part of #790

**Comment by grtlr** [comment]
This was closed by #821.
