### ISSUE TITLE
Missing field `milestone` error when INX connection establishes too quickly

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#758]
Sometimes, when the INX connection between the node and Chronicle is established very quickly the optional `milestone` field is sometimes not present yet. In these cases we should `WARN` and try again. Here are the corresponding lines in protobuf: https://github.com/iotaledger/inx/blob/develop/proto/inx.proto#L130-L131

**Comment by grtlr** [comment]
I can reproduce this from time to time by starting Hornet from scratch (i.e. delete the snapshot files and database).

**Comment by Alex6323** [comment]
Yea, I've seen it, too, now.
