### ISSUE TITLE
Ensure that `TreasuryOutput`s are handled correctly

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#783]
As per @alexsporn, `inx::ListenToLedgerUpdates` does not stream `TreasuryOutputs`. Because of this, they will also not end up in our `OutputCollection`, which in turn means that we can't retrieve such a block in our `BlockCollection::get_block` call.

While we are solving this, we should really rethink how we handle Treasury updates. This has not been important for Shimmer, because there is no Treasury there, but we have to figure this out for Stardust on IOTA.

**Comment by Alexandcoats** [comment]
Still waiting
