### ISSUE TITLE
Chronicle should not use a hard-coded default config

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/inx-chronicle#788]
### Bug description

Currently, if Chronicle is called without arguments (and with the temporarily removed feature of using an `.env` file) it will create a config with default values and start with it. This is confusing at best and most likely not what the user wants as it also contains credentials to MongoDb which in production won't be the default ones. I'ld definitely log if Chronicle is run with a default config, but probably would just abort Chronicle with an appropriate message.

**Comment by grtlr** [comment]
We still need to iterate on the solution, but close this for now.
