### ISSUE TITLE
Missing `BaseToken` from `core/v2/info/`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#803]
The `baseToken` field is missing from Chronicle's response.

**Comment by Alex6323** [comment]
Hmm, that's actually a bit tougher to solve than I initially thought. If we hadn't this requirement of providing the core API without being connected to a node via INX, then we could just forward this information from the node. So we have to either 
(a) create a collection to store that information initially
(b) store that information with the protocol parameters
(c) store that information in the config
