### ISSUE TITLE
Investigate why the `api/explorer/v2/blocks/:block_id/children` is so slow

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/inx-chronicle#815]
It takes roughly 1 minute to fetch this information through this endpoint. Maybe it's missing an index?

Wasn't this the endpoint we considered removing? Maybe we should do so (easy fix :trollface: )

**Comment by Alexandcoats** [comment]
With how much data in the database?

**Comment by Alex6323** [comment]
That was against the full `shimmer` db.

**Comment by Alexandcoats** [comment]
This is definitely because there is no index on `block.parents`. I don't think it's necessary because nobody uses this endpoint anyway. If it becomes a problem, adding the index is trivial. Closing for now.
