### ISSUE TITLE
Total active addresses and optimising this metric / endpoint

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger/inx-chronicle#829]
## Description

I would suggest either defining a time span (i.e. one day, one week) that declares an address as active or creating a second endpoint that involves a time-based activity metric for active addresses.

## Motivation

Most networks aim to display how active their networks are used and especially (if possible) how the activity in a network grows as a sign of adoption. Usual metrics for this are "daily active addresses", "daily active wallets" or a weekly iteration of these.

The current endpoint we are using in the explorer does count every address that either did send or received funds in the network and adds it to the count for "total active addresses" - which leads to an endlessly growing number of active addresses, even if most of them have only been used a single time in history - see the graph for Shimmer: 
![image](https://user-images.githubusercontent.com/77154511/198232408-3a3d8f18-a877-435c-819a-248ce4f2ef99.png)

Honestly, this metric in this setup does not tell us much about the activity in the network.

Afaik the used endpoint has the ability to define a number of milestones during which an address needs to be active to be counted in the Endpoint output.

I suggest defining a reasonable time range for this or creating additional endpoints that give us this information.

So we may end up with endpoints:
1. (ever) used addresses (the currently used setting)
2. daily active addresses
3. weekly active addresses

## Requirements

1.  Decide on the wished timeframes and adjust the endpoint
2. Add additional endpoints
3. 

## Are you planning to do it yourself in a pull request?

No.

**Comment by Alexandcoats** [comment]
The endpoint allows specifying a `startIndex` and `endIndex` for this express purpose.
