### ISSUE TITLE
Fix performance problems with querying analytics

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#847]
### Bug description

Querying for analytics is slow, especially for real-life Shimmer data. Most slow queries come from querying the ledger state at a given milestone index.

A possible fix for this would be to add a compound index on the `booked` and `spent` milestone indexes of an output's metadata.

**Comment by Alexandcoats** [comment]
Have you tried this change to see if it would actually be used by mongo? I found that sometimes I would add indexes thinking they would be used as secondary lookups, only to find that mongo just doesn't use them.
