### ISSUE TITLE
Provide better instrumentation on the tasks that get analytics

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#848]
## Description

There is currently no overview of the total _busy_ and _idle_ time that was required to sync a milestone. Also, the time reporting seems to be off, because we never await the tasks that we spawn (Some of the idle times of the calls inside `get_all_analytics` are much larger than then corresponding milestone sync time).

**Comment by Alexandcoats** [comment]
What do you mean we don't await the tasks?
