### ISSUE TITLE
`v_byte_factor_data` and `v_byte_factor_key` seem to be switched up

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#869]
### Bug description

In comparision with Hornet's `core/v2/info` endpoint our rent structure is messed up. In particular, `v_byte_factor_data` and `v_byte_factor_key` seem to be switched up somewhere in our codebase. I've stumbled upon this when looking at the protocol parameters in InfluxDB.

**Comment by Alexandcoats** [comment]
How certain are we about the `Packable::unpack` impl for `RawProtocolParameters`? I scoured our code and found nothing that could be the cause.

**Comment by grtlr** [comment]
Hmm, could also be a problem with `iota-types`. I'm not sure though.

**Comment by grtlr** [comment]
Related issue: https://github.com/iotaledger/iota.rs/issues/1364
