### ISSUE TITLE
Investigate why Chronicle's `info` endpoint is slow compared to Hornet's.

### ISSUE THREAD

**Issue by Alex6323** [iotaledger/inx-chronicle#878]
Chronicles response time is ~2.5 - 3 times worse than Hornet's for this very endpoint. It's probably worth to compare other `/api/core/v2` endpoints as well.

**Comment by Alex6323** [comment]
Turns out that the performance difference - although there - is less significant when we compare Hornet with Chronicle's production build (~2 times slower in the worst case, and same speed in the best case).

**Comment by grtlr** [comment]
I'm closing this for now, as it does not affect production.
