### ISSUE TITLE
Set `INFLUXDB_DATA_MAX_SERIES_PER_DATABASE` to 0 in `docker-compose.yml`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#886]
Otherwise InfluxDB will stop inserting points once the database is full: https://docs.influxdata.com/influxdb/v1.8/administration/config/#max-series-per-database-1000000

**Comment by Alexandcoats** [comment]
Annoying

**Comment by grtlr** [comment]
While we're at it we also should set this variable: `INFLUXDB_DATA_MAX_VALUES_PER_TAG=0`

This has also been causing problems.

**Comment by Alexandcoats** [comment]
Any concerns about these default values and the longevity of data in influx?
