### ISSUE TITLE
Implement binary format for POIs

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#890]
## Description

We should return a binary endpoint for the POIs, similar to the binary endpoints in the Core Node API.

## Motivation

Should save some space.

## Requirements

1. Define format.
2. Implement it.
3. Document the endpoint in the Swagger file.

## Open questions (optional)

* Settle on format.
* Investigate file size improvements.

## Are you planning to do it yourself in a pull request?

No.

**Comment by Alex6323** [comment]
We came to the conclusion that a binary format is not worth pursuing until there's an actual demand for it. A custom format has the potential of getting rid of some redundancies, but there's no empirical data yet about certain usage patterns. JSON on the other hand is an ubiquitous, future-proof, and widely supported format, that better guarantess that such proofs of inclusion can be validated in the future. If storing them is of any concern then clients can still convert and compress them as they see fit using standard algorithms.
