### ISSUE TITLE
Fix index creation on fresh start up

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#892]
### Bug description

It currently looks like indexes are not properly build, or at least take a long time to build initially. It also seems like we are thrashing them right away (writing to the collections while the indexes are still being build). This leads to slow sync times.

The current solution is to restart the node after a while, which improves sync times a little bit, but I think we can do better.

**Comment by Alexandcoats** [comment]
Of course we can do better, we can switch to postgres :trollface:
