### ISSUE TITLE
Unclaimed token analytics is not monotonously decreasing

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#906]
### Bug description

For the Shimmer Grafana dashboard (this happens between `2022-10-02 06:37:23` and `2022-10-02 17:03:56`):

<img width="2135" alt="image" src="https://user-images.githubusercontent.com/3404250/202719007-e001bdae-1834-4719-b80f-0fb52410add7.png">

**Comment by grtlr** [comment]
Here is a screenshot of the entire Shimmer history, something looks wrong:
<img width="2149" alt="image" src="https://user-images.githubusercontent.com/3404250/202994314-0786f2f9-4205-4af1-87ab-1e26a5d0c370.png">

**Comment by Alexandcoats** [comment]
Is there a source of truth we can compare with here?

**Comment by grtlr** [comment]
This bug has been fixed by one of our PRs, at least I don't see it happening on the complete Shimmer history anymore. Closing this for now.
