### ISSUE TITLE
Provide more options to `fill-analytics`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#916]
## Description

It would be nice to have the option to specify only a subset of measurements that should be resynced. This way we could skip syncing of measurements that are expansive to compute. Ideally, those could also be configured through the `config.toml`.

Maybe something like `inx-chronicle fill-analytics --measurements "ledger_size storage_deposit"`.

**Comment by Alexandcoats** [comment]
Who is this for?
