### ISSUE TITLE
Add information about the token distribution to InfluxDB

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#951]
## Description

We already have a MongoDB query for retrieving the token distribution. We should also push this information to InfluxDB to make it possible to analyze changes in that distribution over time.

**Comment by Alexandcoats** [comment]
This is one of the slowest queries, one of the worst ones to make incremental, AND a difficult one to display in grafana. Not sure this is worth it.

**Comment by Alex6323** [comment]
Yeah, I agree with everything you wrote, but it seems to be something people are interested in (I myself find it quite interesting, too).

**Comment by grtlr** [comment]
Good points @Alexandcoats! I have a good way how to visualize them in mind for Grafana, so that shouldn't be a problem. Regarding the performance, with #949 we can run queries only for certain timestamps, so how about we only compute this distribution on a daily basis? @Alex6323 is right, this metric is very important to the IF.
