### ISSUE TITLE
`fill-analytics` with `-n 10` makes per milestone time drop significantly

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#959]
### Bug description

<img width="2142" alt="image" src="https://user-images.githubusercontent.com/3404250/205666552-37f07fe9-a3d5-41bb-ad6b-4716f59b4897.png">

The sync time per milestone is higher when running with `-n 10`, also the variation in sync time is higher. One reason for this could be the access pattern for the data (interleaving).

We should investigate if we can improve this to speed up the syncing process.

**Comment by Alexandcoats** [comment]
Are you running the command in parallel with the syncing process?

**Comment by grtlr** [comment]
No.

**Comment by Alexandcoats** [comment]
Should be fixed by #1061
