### ISSUE TITLE
Current parallelization strategy for `fill-analytics` does not acount for daily statistics

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#970]
### Bug description

When we rework the parallelization strategy in #959, we should also think about how to avoid duplicate computation of daily statistics per task. Right now the daily activity analytics just look of the date has changed from one milestone timestamp to the next. Of course, this would happen for every task, so we would potentially do the same daily computations over and over again for each task.

**Comment by Alexandcoats** [comment]
Closed by #1061

**Comment by Alexandcoats** [comment]
Closed by #1070
