### ISSUE TITLE
Gathering metrics can become bottleneck during `fill-analytics`

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#971]
### Bug description

When we only collect daily statistics, collecting the analytics metrics can slow down the syncing speed, because writing to InfluxDB takes longer than skipping over uninteresting milestones.

We should think about strategies to mitigate this, or rework our `fill-analytics` logic in general (for example by splitting the logic into _per milestone_ and _time interval_ analytics).

**Comment by Alexandcoats** [comment]
Closed by #1131
