### ISSUE TITLE
`total_storage_deposit_value` analytic is wrong

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#996]
Our definition of `total_storage_deposit_value` is wrong:

https://github.com/iotaledger/inx-chronicle/blob/6ec481cc2200c7e7990770c2f20ace336bc0b3e7/src/db/collections/analytics/ledger_size.rs#LL78C21-L78C21

In addition to the _storage deposit return unlock condition amount_ we should also track to total required storage cost (i.e. the _total_byte_cost_).

**Comment by Alexandcoats** [comment]
I'm a little confused. Isn't this performed by the `total_byte_cost` fn on `LedgerSizeAnalyticsResult`?

**Comment by grtlr** [comment]
You're right. The thing is we never right the result of that function to Influx. We would have to query the current protocol parameters in `LedgerSizeAnalytics::get_measurement` and then feed if into a derived `LedgerSizeAnalyticsDerivedResult`. Or, alternatively, we do this computation as part of the actual MongoDB query.
