### ISSUE TITLE
Create separate binary for APIs

### ISSUE THREAD

**Issue by grtlr** [iotaledger/inx-chronicle#997]
## Description

We should create a separate binary (potentially even an own crate) for the API part of Chronicle. This is straightforward now that all our configuration is `docker-compose.yml`-based.

## Motivation

This would make versioning of Chronicle a lot simpler.

**Comment by Alexandcoats** [comment]
We would likely have to maintain 3 separate crates vs the one right now.

**Comment by grtlr** [comment]
The more I think about it the more disadvantages I see with this, which is why I'm closing this for now.
